/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function DanceModel(props: any) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/dance.glb");
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group
					name="Armature"
					position={[2.53, -0.64, -9.54]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.04}>
					<primitive object={nodes.mixamorigHips} />
					<skinnedMesh
						name="Beta_Joints"
						geometry={nodes.Beta_Joints.geometry}
						material={materials.Beta_Joints_MAT1}
						skeleton={nodes.Beta_Joints.skeleton}
					/>
					<skinnedMesh
						name="Beta_Surface"
						geometry={nodes.Beta_Surface.geometry}
						material={materials.Beta_HighLimbsGeoSG3}
						skeleton={nodes.Beta_Surface.skeleton}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/dance.glb");
