/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function DeskModel(props: any) {
	const { nodes, materials } = useGLTF("/Desktop.glb");
	return (
		<group
			position={[0, -1, 1.02]}
			scale={[0.41, 0.4, 0.53]}
			rotation={[1, 3.1, 0]}
			{...props}
			dispose={null}>
			<group scale={[4.7, 0.11, 2.27]}>
				<mesh geometry={nodes.Cube001.geometry} material={materials.TableTop} />
				<mesh geometry={nodes.Cube001_1.geometry} material={materials.Metal} />
			</group>
			<mesh
				geometry={nodes.Monitor.geometry}
				material={materials.Monitor}
				position={[0, 0.14, 1.12]}
				scale={[0.71, 0.03, 0.53]}
			/>
			<group position={[0.67, 0.21, -0.69]} scale={[1.12, 0.09, 0.45]}>
				<mesh geometry={nodes.Cube002_1.geometry} material={materials.KBBase} />
				<mesh geometry={nodes.Cube002_2.geometry} material={materials.KBEsc} />
				<mesh
					geometry={nodes.Cube002_3.geometry}
					material={materials.KBExtras}
				/>
				<mesh geometry={nodes.Cube002_4.geometry} material={materials.KBMain} />
			</group>
			<group
				position={[-1.07, 0.25, -0.5]}
				rotation={[Math.PI, 0, Math.PI / 2]}
				scale={[0.05, 0.02, 0.04]}>
				<mesh
					geometry={nodes.Cylinder001_1.geometry}
					material={materials.KBExtras}
				/>
				<mesh
					geometry={nodes.Cylinder001_2.geometry}
					material={materials.KBMain}
				/>
				<mesh
					geometry={nodes.Cylinder001_3.geometry}
					material={materials.KBEsc}
				/>
			</group>
			<mesh
				geometry={nodes.Cube002.geometry}
				material={materials.MP}
				position={[0, 0.12, -0.63]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-2.71, -0.02, -0.97]}
			/>
			<group position={[3.04, -1.18, -0.4]} scale={[0.56, 0.94, 0.94]}>
				<mesh geometry={nodes.Cube006.geometry} material={materials.USB} />
				<mesh geometry={nodes.Cube006_1.geometry} material={materials.Red} />
				<mesh geometry={nodes.Cube006_2.geometry} material={materials.Yellow} />
				<mesh geometry={nodes.Cube006_3.geometry} material={materials.Green} />
				<mesh geometry={nodes.Cube006_4.geometry} material={materials.Case} />
			</group>
			<mesh
				geometry={nodes.MonitorScreen.geometry}
				material={materials.Screen}
				position={[0, 0.14, 1.12]}
				scale={[0.71, 0.03, 0.53]}
			/>
			<group
				position={[3.63, 0.63, 0.91]}
				rotation={[-2.39, -0.66, 0.54]}
				scale={[0.19, 0.46, 0.09]}>
				<mesh
					geometry={nodes.Cylinder013.geometry}
					material={materials["Leaf.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder013_1.geometry}
					material={materials["Soil.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder013_2.geometry}
					material={materials.Pot}
				/>
			</group>
			<group
				position={[-3.5, 0.63, 0.99]}
				rotation={[-2.55, -0.26, 0.19]}
				scale={[0.19, 0.46, 0.09]}>
				<mesh
					geometry={nodes.Cylinder003.geometry}
					material={materials["Leaf.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder003_1.geometry}
					material={materials["Soil.001"]}
				/>
				<mesh
					geometry={nodes.Cylinder003_2.geometry}
					material={materials.Pot}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/Desktop.glb");
