/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";
import useMediaQuery from "../utils/useMediaQuery";

export default function Model(props: any) {
	const { nodes, materials } = useGLTF("/title.glb");
	const matches = useMediaQuery("(max-width: 640px)");

	console.log(matches);
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Text.geometry}
				material={nodes.Text.material}
				position={matches ? [-4.24, 10, -14] : [-4.24, 3, -4]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
		</group>
	);
}

useGLTF.preload("/title.glb");
